project:
  type: website
  output-dir: docs
  
website:
  title: "Hans' Portfolio (WIP)"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - projects.qmd
      - ST_Rental.qmd

    tools:
      - icon: github
        href: https://github.com/HDB-Q/AboutMe
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Hans B"

format:
  html:
    theme: 
      light: [litera, styles.scss]
      dark: [solar, styles-dark.scss]
    toc: true

editor: source