project:
  type: website
  output-dir: docs
  
website:
  title: "Work in Progress"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - newfile.qmd
    tools:
      - icon: twitter
        href: https://twitter.com/
      - icon: github
        href: https://github.com/HDB-Q/AboutMe
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"
    left: "&copy; Copyright 2024, Hans B"

format:
  html:
    theme: pulse
    toc: true

editor: source