---
title: EHN Project
filters:
  - lightbox
lightbox: auto
---

## Meet the Team

[Lynn Liu](https://linkedin.com/in/yixuan-lynn-liu), [Hans Bisoo](https://linkedin.com/in/hans-dilchand), and [Timothy Williams](https://linkedin.com/in/i-am-timothy-williams) are part of the final EHN Canada team. EHN Canada specializes in treating all types of addictions and related mental health concerns including depression, anxiety, trauma and PTSD, and eating disorders 

We were tasked to optimize a bottleneck facing the Admissions Team, who field 10,000+ inquiries per month via discovery dialogue. Information retrieval during that process requires the appropriate medical background as well as EHN's offerings and nuances. 

We built an AI Platform to support a real-time chat bot for internal use that draws from internal knowledge bases and a simple platform to handle knowledge base updates. Evaluations using `DeepEval` were instrumental in building the continuous integration pipeline, as well as selecting our software defaults. Our AI platform is build on open-source tools and uses local models. 
