---
title:        Title
subtitle:     Subtitle
description: |
  A qmd quarto template document.
abstract: |
  Document abstract may be somewhat long.
author:
  - name:   Erik Erhardt
    url:    https://StatAcumen.com/about
    email:  erike@stat.unm.edu
    orcid:  0000-0002-9817-4011
    note:   Statistician and statistical programmer.
    affiliations:
      - name:         University of New Mexico
        department:   Department of Mathematics and Statistics
        address:      1 University of New Mexico, MSC01 1115
        city:         Albuquerque
        region:       NM
        country:      USA
        postal-code:  87131
        url:          https://www.math.unm.edu/people/academic-personnel/erik-erhardt
date:         last-modified # today, now, last-modified
#date-format:  long          # full, long, medium, short, iso,   https://quarto.org/docs/reference/dates.html
date-format:  "MM/DD/YYYY \\ hh:mm:ss A ZZ"
citation:
  url: https://StatAcumen.com
google-scholar:     true
author-title:       Author
affiliation-title:  Affiliation
abstract-title:     Abstract
description-title:  Description
published-title:    Published
doi-title:          DOI
appendix-style:     default     # plain, default, none  # https://quarto.org/docs/authoring/appendices.html
lang:               en
format:
  html:
    #theme:
    #  light: flatly
    #  dark: darkly
    theme:                  litera    # default, cerulean, cosmo, cyborg, darkly, flatly, journal, litera, lumen, lux, materia, minty, morph, pulse, quartz, sandstone, simplex, sketchy, slate, solar, spacelab, superhero, united, vapor, yeti, zephyr
    highlight-style:        atom-one  # a11y, arrow, atom-one, ayu, breeze, github, gruvbox; pygments, tango, espresso, zenburn, kate, monochrome, breezedark, haddock; dracula, mokokai, nord, oblivion, printing, radical, solarized, vim-dark
    page-layout:            full      # article, full   # https://quarto.org/docs/output-formats/page-layout.html
    toc:                    true
    toc-depth:              4
    toc-location:           body      # left, body, right
    toc-title:              Contents
    number-sections:        true      # true, false
    number-depth:           5
    code-fold:              show      # true (initially hidden), false, show (initially shown)
    code-tools:                       # menu top-right to show/hide all code
      toggle:               true
      caption:              "Code"    # none
      source:               false
    code-summary:           "Code"    #, click to show"
    code-overflow:          scroll    # scroll, wrap
    code-block-bg:          true
    code-block-border-left: "#30B0E0"
    code-copy:              hover     # true, false, hover a copy buttom in top-right of code block
    df-print:               paged     # default, kable, tibble, paged   # https://quarto.org/docs/computations/r.html
    self-contained:         false     # !!! this can cause a render error: "ERROR: The process cannot access the file because it is being used by another process. (os error 32)"
    self-contained-math:    true
    link-external-icon:       false   # true, false an icon after the link to indicate external
    link-external-newwindow:  false   # true, false
    link-external-filter:     ^(?:http:|https:)\/\/statacumen\.com
    #html-math-method: katex    # https://quarto.org/docs/output-formats/html-basics.html
  pdf:                                # Quarto uses KOMA Script document classes by default  https://ctan.org/pkg/koma-script
    latex-auto-mk: true               # true, false  # run the pdf-engine more than once to generate your PDF
    #pdf-engine: lualatex
    #pdf-engine-opt: -outdir=out
    #include-in-header:
    #  - text: |
    #      \usepackage{eplain}
    #      \usepackage{easy-todo}
    #  - file: packages.tex
    #  - macros.tex
    keep-tex:               true      # keep .tex file that is produced
    documentclass:          scrartcl  # article, report, book, scrartcl, scrreprt, scrbook
    papersize:              letter
    classoption:            [oneside,11pt] # [twocolumn, landscape]
    geometry:
      - margin = 1in
      #- top  = 30mm
      #- left = 20mm
      #- heightrounded
    fontfamily:             libertinus
    cite-method:            biblatex
    #biblatexoptions List of options for biblatex
    #natbiboptions List of options for natbib
    #biblio-title  Title for bibliography
    #biblio-style  Style for bibliography
    toc:                    true
    toc-depth:              4
    toc-title:              Contents
    number-sections:        true
    number-depth:           5
    lof:                    true
    lot:                    true
    colorlinks:             true
    highlight-style:        atom-one  # a11y, arrow, atom-one, ayu, breeze, github, gruvbox; pygments, tango, espresso, zenburn, kate, monochrome, breezedark, haddock; dracula, mokokai, nord, oblivion, printing, radical, solarized, vim-dark
title-block-style:          default   # plain, none
title-block-banner:         false     # background color: true, false, "#95b7fc"
title-block-banner-color:   "#232323" # text color: "#232323"
fig-width:                  6
fig-height:                 4
fig-align:                  center    # default, left, right, or center
fig-cap-location:           bottom    # bottom, top, margin
tbl-cap-location:           top       # top, bottom, margin
callout-appearance:         default   # default, simple, minimal
reference-location:         section   # document, section, block, margin
citation-location:          document  # document, margin
crossref: # https://quarto.org/docs/authoring/cross-references.html
  fig-title:        Figure  # (default is "Figure")
  tbl-title:        Table   # (default is "Table")
  title-delim:      ":"     # (default is ":")
  fig-prefix:       Figure  # (default is "Figure")
  tbl-prefix:       Table   # (default is "Table")
  ref-hyperlink:    true    # (default is true), false
  labels:           arabic  # (default is arabic)
  subref-labels:    alpha a # (default is alpha a)
  chapters:         true
  lof-title:        List of Figures
  lot-title:        List of Tables
execute: # https://quarto.org/docs/computations/execution-options.html, https://quarto.org/docs/computations/r.html
  cache:    false   # false, true
  #freeze:  auto    # auto = re-render only when source changes, true, false
  eval:     true    # true, false  Evaluate the code chunk (if false, just echos the code into the output).
  echo:     true    # true, false  Include the source code in output
  output:   true    # true, false  Include the results of executing the code in the output (true, false, or asis to indicate that the output is raw markdown and should not have any of Quarto’s standard enclosing markdown).
  message:  true    # true, false  Include messages in the output.
  warning:  true    # true, false  Include warnings in the output.
  error:    true    # true, false  Include errors in the output (note that this implies that errors executing code will not halt processing of the document).
  include:  true    # true, false  Catch all for preventing any output (code or results) from being included (e.g. include: false suppresses all output from the code block).
---

<!---
# Erik's compile commands in R:
  setwd("D:/Dropbox/StatAcumen/consult/Rpackages/erikmisc/data-raw/qmd_template")
  fn_qmd <- "erik_qmd_template.qmd"
  quarto::quarto_render(input = fn_qmd)
-->

```{r chunk-01, echo=FALSE}
options(width = 80)
#options(warn  = -1)
options(str   = strOptions(list.len = 1e3))
options(knitr.kable.NA = '') # Display NAs as blanks
my_seed <- 34567
set.seed(my_seed)
```

{{< pagebreak >}}

# Executive summary {#sec-Executive_summary}

{{< pagebreak >}}

# Introduction {#sec-Introduction}

## Background/rationale

* Explain the scientific background and rationale for the investigation being reported

## Objectives

* State specific objectives, including any prespecified hypotheses

## Literature Review:

* Review of relevant prior research and theories.
* Identification of gaps in existing knowledge.

{{< pagebreak >}}

# Methods {#sec-Methods}

## Study design

* Present key elements of study design early in the paper

## Setting

* Describe the setting, locations, and relevant dates, including periods of recruitment, exposure, follow-up, and data collection

## Participants

* Cohort study --- Give the eligibility criteria, and the sources and methods of selection of participants. Describe methods of follow-up
* Case-control study --- Give the eligibility criteria, and the sources and methods of case ascertainment and control selection. Give the rationale for the choice of cases and controls
* Cross-sectional study --- Give the eligibility criteria, and the sources and methods of selection of participants
* Cohort study --- For matched studies, give matching criteria and number of exposed and unexposed
* Case-control study --- For matched studies, give matching criteria and the number of controls per case

## Variables

* Clearly define all outcomes, exposures, predictors, potential confounders, and effect modifiers. Give diagnostic criteria, if applicable

## Data sources/measurement

* Give information separately for cases and controls in case-control studies and, if applicable, for exposed and unexposed groups in cohort and cross-sectional studies.
* For each variable of interest, give sources of data and details of methods of assessment (measurement). Describe comparability of assessment methods if there is more than one group

## Bias

* Describe any efforts to address potential sources of bias

## Study size

* Explain how the study size was arrived at

## Quantitative variables

* Explain how quantitative variables were handled in the analyses. If applicable, describe which groupings were chosen and why

## Statistical methods

* Describe all statistical methods, including those used to control for confounding
* Describe any methods used to examine subgroups and interactions
* Explain how missing data were addressed
* Cohort study --- If applicable, explain how loss to follow-up was addressed
* Case-control study --- If applicable, explain how matching of cases and controls was addressed
* Cross-sectional study --- If applicable, describe analytical methods taking account of sampling strategy
* Describe any sensitivity analyses

{{< pagebreak >}}

# Results {#sec-Results}